### PR TITLE
Custom image tags and chained docker-compose files.

### PR DESCRIPTION
**Pull request by L226**
Just some quick stuff to get the functionality we needed.
- Needed custom image tags on images uploaded to a docker repository for our production environment - I've added this functionality as an environment variable.
- Additionally we needed to be able to extend our base docker-compose.yml with docker-compose.test.yml and similar for running test suites without having to rebuild entire containers. Have added this as an environment variable. The existing config option did not suit our needs.
- I've also updated the readme with relevant changes.

Happy to discuss, feel free to comment.

### CODE REVIEW

**Comment by L226** [comment]
yeah I had some fun testing stuff, been a while since I've written shell :)

**Comment by sj26** [comment]
Thank you for your contribution!

It looks like this adds multiple tags and multiple docker compose files. Would #3 and #7 provide enough for your use case?

**Comment by jufemaiz** [comment]
@L226 can you please provide some feedback on @sj26 comments? 👍

**Comment by sj26** [comment]
We've merged in #3 which should sort out the multiple docker compose files, please check out [the documentation](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#example).

I've also extracted my changes to #7 as #9, maybe take it for a spin with:

```yaml
steps:
  - command: test.sh
    plugins:
      docker-compose#custom-tags:
        build: app
        image-repository: org/repo
        tags:
          - my-tag
```

**Comment by L226** [comment]
Alright I'll have a look

**Comment by toolmantim** [comment]
Probably worth closing this one for now, with all the changes that have been merged! If you spot anything you still want to add, want to send through fresh PRs?

**Pull request closed without merging**
