### PR TITLE
Add entrypoint property to plugin.yml

### PR DESCRIPTION
**Pull request by evandam**
Fixes https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/299

This works for something like:

```yaml
steps:
  - label: "test"
    plugins:
      - evandam/docker-compose#9faddab:
          run: test-app
          entrypoint: "echo"
          command: ["hello entrypoint"]
```

### CODE REVIEW

**Comment by evandam** [comment]
Hey folks, not sure who to ping to get a review on this - cc @toolmantim @pda maybe?

**Comment by toolmantim** [comment]
Thanks @evandam! Sorry for the delay in the review. Looks great 👍🏼

**Comment by evandam** [comment]
Thanks @toolmantim! Just wondering when we can expect to see the next release with this included. Looking forward to cleaning up a fewe pipelines with this :joy:

**Comment by evandam** [comment]
@toolmantim can we get a release for this? 🚀

**Comment by scalp42** [comment]
@lox maybe?

**Pull request merged**
