### PR TITLE
add graceful shutdown

### PR DESCRIPTION
**Pull request by calvin-pietersen**
add GRACEFUL_SHUTDOWN to stop containers
add GRACEFUL_SHUTDOWN test

### CODE REVIEW

**Comment by lox** [comment]
Interesting! Would love to know a bit more about what prompted this change @calvin-pietersen!

**Comment by calvin-pietersen** [comment]
@lox Yes, we have a scenario where one of our dependant containers needs to output an artefact. Which can only be done by gracefully shutting down the container :(

**Comment by jathu** [comment]
@toolmantim can we merge?

**Comment by toolmantim** [comment]
Sorry for the delay @jathu! That's been merged, and a release will be out soon.

**Pull request merged**
