### PR TITLE
Add volume support for run

### LINKED ISSUE #148: volume support
It would be really great if we could specify volumes alongside env vars for each `run` service.

### PR DESCRIPTION
**Pull request by clee**
Fixes #148.

### CODE REVIEW

**Comment by lox** [comment]
Thanks for this @clee! I'm ok to add this, would it be possible to add a README entry? Ideally we'd get a test too, but I can help with that if need be.

**Comment by clee** [comment]
Good call, @lox! This PR has been updated with new documentation in the README. I attempted to match the tone and style of the existing documentation, but I'm happy to adjust it (or for y'all to change it).

**Comment by toolmantim** [comment]
Thanks for the PR @clee! I've just rebased this, added some tests for you.

One thing I noticed, is that it seems to support both `vol` and `volumes` — but I've only tested for the latter. What do you think about me removing `vol` support?

**Comment by clee** [comment]
It lines up nicer with `env` but that’s literally the only reason I implemented it. I’m fine with you taking it out!

**Comment by toolmantim** [comment]
Ok cool, thanks for the backstory.

The `env` is there because we have the same alias for the `env` in command steps in the pipeline.yml  — so you can copy+paste. But because there's no `vol` equivalent, we can probably remove it from here.

I'll do that now, and merge! 🎉

**Pull request merged**
