### PR TITLE
Don't attempt to output containers when using 'rm'

### PR DESCRIPTION
**Pull request by ags**
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/211 added a '--rm' to the docker-compose commands in addition to the container cleanup done in the pre-exit hook.

This appears to silently break the check for linked log file uploads as no containers will be returned by `docker ps`, and conflicts with the changes in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/212 to output failed containers for the same reason, though the later fails loudly as no containers are passed to `docker inspect` (the former uses a more graceful loop).

The test suite was also broken due to conflicts between these two changes.

To fix things this tests for the 'rm' configuration and doesn't attempt to output failed containers or upload logs when present. That's not ideal as it's a bit unexpected; it would probably be worth reconsidering whether 'rm' should be enabled by default, and implementing a more graceful version of the failed container output check.

See https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/220

### CODE REVIEW

**Comment by toolmantim** [comment]
Cc @pecigonzalo

**Comment by pecigonzalo** [comment]
Nice catch, odd as I ran a branch that has both these things without this problem (minus some small fixed we did at the end). Let me investigate, as the `--rm` did not affect this in my case.

**Comment by pecigonzalo** [comment]
@williams4027 @ags could you confirm your docker-compose only contains 1 container definition? I believe the problem is related to that. 

We should not skip collecting logs on `--rm` but rather split the inspect here: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/212/files#diff-9ae713e61df74a2c7813f885fca363aeR267 to do it only if `docker_ps_by_project -q` has containers (there are none if only 1 container ran)

**Comment by williams4027** [comment]
@pecigonzalo Just to make sure I give you the right information, my docker-compose.buildkite.yml that was being used has multiple (5) services defined, but the build step in the pipeline only targeted a single one:

```
"docker-compose" => {
  "config" => "docker-compose.buildkite.yml",
  "run" => "app"
}
```

Logs:
```
  | Building Docker Compose Service: app | 0s
  | ⚠️ No pre-built image found from a previous 'build' step for this service and config file. Building image...
  | $ docker-compose -f docker-compose.buildkite.yml -p buildkite84539356acc44c3bb7c4848875eb9614 build --pull app
  | app uses an image, skipping
  |  
  | Starting dependencies | 1s
  | $ docker-compose -f docker-compose.buildkite.yml -p buildkite84539356acc44c3bb7c4848875eb9614 up -d --scale app=0 app
  | Creating network "buildkite84539356acc44c3bb7c4848875eb9614_default" with the default driver
```

**Comment by pecigonzalo** [comment]
@williams4027 and does it have any `depends_on` or `linked` containers? as in, does it start any other container if you start it?

**Comment by williams4027** [comment]
Correct, that one specifically did not, no. Only a volume mount.

But other build steps in the same pipeline used this plugin and target `appwithserver`, which has `links` to other services. Those steps with multiple containers starting up did not fail. So I believe the idea that this only affects when a single container is started up for a step is correct based on my experience.

**Comment by pecigonzalo** [comment]
I think a change like so:
```
❯ git diff              
Alias tip: gd
diff --git i/commands/run.sh w/commands/run.sh
index ec42d46..1f529bd 100755
--- i/commands/run.sh
+++ w/commands/run.sh
@@ -274,11 +274,15 @@ fi
 if [[ -n "${BUILDKITE_AGENT_ACCESS_TOKEN:-}" ]] ; then
   if [[ "$(plugin_read_config CHECK_LINKED_CONTAINERS "true")" != "false" ]] ; then
 
+    containers=($(docker_ps_by_project -q))
+
     # Get list of failed containers
-    failed_containers=($(
-      docker inspect -f '{{if ne 0 .State.ExitCode}}{{.Name}}.{{.State.ExitCode}}{{ end }}' \
-      $(docker_ps_by_project -q)
-    ))
+    if [[ 0 != "${#containers[@]}" ]] ; then
+      failed_containers=($(
+        docker inspect -f '{{if ne 0 .State.ExitCode}}{{.Name}}.{{.State.ExitCode}}{{ end }}' \
+        ${containers}
+      ))
+    fi
 
     if [[ 0 != "${#failed_containers[@]}" ]] ; then
       echo "+++ :warning: Some containers had non-zero exit codes"
```

Should be enought to fix this issue

**Comment by ags** [comment]
Right, that makes sense. I'll close this and leave you to fix that then @pecigonzalo.

**Pull request closed without merging**
