### PR TITLE
support build args

### PR DESCRIPTION
**Pull request by chronotc**
WIP

### CODE REVIEW

**Comment by lox** [comment]
This is looking really good @chronotc!

**Comment by lox** [comment]
This seems pretty close, what did you have left to do @chronotc?

**Comment by chronotc** [comment]
Sorry for taking so long. I was going to write a proper description and manually test it but haven't had time outside of work to do that. Apart from that, I think it has everything it needs to support build args.

**Comment by lox** [comment]
I'm gonna merge it and we can iterate on the other bits! Thanks so much @chronotc!

**Pull request merged**
