### PR TITLE
Cleanup readme, schema and tests for build args to `run` steps

### PR DESCRIPTION
**Pull request by DuBistKomisch**
This was originally https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/250 but was reverted in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/261 due to some CI issue. Just recreating this so that it doesn't get forgotten.

Happy to help fix any issues but I can't access the builds. My assumption is it's the additon of the `args` to the schema? Maybe we should just remove them since they weren't there in the first place.

### CODE REVIEW

**Comment by toolmantim** [comment]
Hi @DuBistKomisch! Have fixed up the builds now, so you should be able to push new commits to get a fresh build. Another option is to install the [bk cli](https://github.com/buildkite/cli) to run the pipeline locally.

**Comment by DuBistKomisch** [comment]
Thanks, took the opportunity to just rebase against master. Can see the issue now, I'll fix it tomorrow!

**Comment by DuBistKomisch** [comment]
Turns out this is mostly redundant with https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/235, so this is just some README/schema fixes and extra tests now.

**Comment by toolmantim** [comment]
Thanks @DuBistKomisch! I’ve just updated the title to cover that. Looks great! Appreciate it, and sorry it took so long.

**Pull request merged**
